services:
  pihole-dhcp-controller:
    container_name: pihole-dhcp-controller
    build: .
    restart: unless-stopped
    
    # Load configuration variables from the .env file.
    # Make sure you have created a .env file (by copying from .env.example)
    # and filled it with your data.
    env_file: .env
